name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" # her gün çalışır
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Generate GitHub contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: yaseminozhan
          outputs: |
            ./output/github-contribution-grid-snake.svg
            ./output/github-contribution-grid-snake.gif

      - name: Push to output branch
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate contribution snake"
